version: 2

updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"

  - package-ecosystem: "mix"
    directory: "/examples/phoenix_checkout"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(example)"
      prefix-development: "deps-dev(example)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
